language: node_js
node_js:
  - "7"
  - "6"
  - "4"
before_script:
  - npm install -g gulp mocha gulp-cli
install:
  - npm install
script: 
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)