sudo: false
language: node_js
services: mongodb
env:
  - MONGOLAB_URL=mongodb://127.0.0.1/snipe
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
node_js:
  - '7'
  - '6'
before_script:
  - sleep 15
  - npm install -g gulp mocha gulp-cli codecov istanbul
install:
  - npm install
script:
  - >-
    istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    && codecov
