language: node_js
services: mongodb
env:
  - MONGOURL=mongodb://127.0.0.1/snipe
node_js:
  - '7'
  - '6'
before_script:
  - npm install -g gulp mocha gulp-cli codecov istanbul
install:
  - npm install
script:
  - >-
    istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    && codecov
