sudo: false
language: node_js
services: 
  - mongodb
  - redis-server
env:
  - MONGOLAB_URL=mongodb://127.0.0.1/snipe RATE_LIMIT=10 REDIS_URL=redis://127.0.0.1/1 SECURE_MODE=true NO_CACHE=no ENFORCE_USER_ID_APP_ID_DEVELOPER_ID=yes
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
node_js:
  - '7'
  - '6'
before_script:
  - sleep 15
  - npm install -g gulp mocha gulp-cli codecov istanbul
install:
  - npm install
script:
  - >-
    istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    && codecov
